### ISSUE TITLE
Good place to start?

### ISSUE THREAD

**Issue by Mesaj2000** [hackingmaterials/pv-vision#2]
Hello. I'm looking to start using this program to classify solar cells, but I'm having some trouble getting started. So far I've reviewed the transform_seg and rf_train_inference tutorials, and transform_module_v2 in useful tools. For each of these the main thing missing is the "ann", but I'm not sure what that is. From what I could gather from the transform_seg tutorial it's a json file with an "objects" element that stores "manual annotations", but other than that I'm not sure. Am I supposed to supply this data on my own? If so what data goes in it? If this is totally the wrong direction and I should start elsewhere that's fine too, just let me know. Thanks!

**Comment by X-Chen97** [comment]
Hi! Thank you for your interest in our package. We haven't provided sample images for practice due to NDA. I am really sorry that you can only use your own data right now. However, the good news is that our data provider has approved sharing some data. We will upload them for practice very soon(in 1~2 weeks)! Please come back and check it then. We sincerely hope you could enjoy using our tools and provide your valuable feedback!
