### ISSUE TITLE
tool to open annotation?

### ISSUE THREAD

**Issue by davidvct** [hackingmaterials/pv-vision#6]
Hi, what tool do we need to open those examples annotation files? I tried CreateML in labelImg but it doesn't work.

**Comment by X-Chen97** [comment]
Hi!

Our annotations were made with Supervisely (https://supervise.ly/), so you can directly use that platform to visualize the annotations. 

Also, you can use load_mask as shown in this old tutorial: https://github.com/hackingmaterials/pv-vision/blob/main/tutorials/old_inactive_area.ipynb. Please note that I updated PV-Vision a lot in the last few months so this tutorial may be out of date. I will also update all these tutorials in the next few weeks.

Apart from that, I will add more functions to PV-vision so that people do not need to use Supervisely to visualize the annotations or deploy the models.
